### PR TITLE
issue-78: Added play beep code in VoiceInterpreter

### PR DESCRIPTION
**Pull request by maria-farooq**
issue-78: Added play beep code in VoiceInterpreter, @gvagenas Please review

### CODE REVIEW

**Comment by gvagenas** [comment]
Hi @maria-farooq. I checked you work and its working great, good job !

We will need one more thing for this issue. We need to provide different sound when someone enters the conference and when exists the conference. 

In that regards please check what it is needed to make this configurable at restcomm.xml. By default you should provide entry=beep.wav, exit=alert.wav

In case that the configurable definition of the entry and exit sounds is too much work, you can simply change the wave file that plays on exit to use the  "alert.wav".

Thanks

**Comment by maria-farooq** [comment]
Thanks @gvagenas it totally makes sense, let me do some study and changes accordingly and i will update you.
Thanks for your review and encouragement,
Maria

**Comment by maria-farooq** [comment]
Hi @gvagenas i have tested and commited changes, i have made audio files configureable in restcomm.xml.
If not found in config, by default entry=beep.wav, exit=alert.wav will be played on entry and exit respectively. 
I noticed a docbook chapter also contained guide about restcomm.xml so i updated that as well.
Please review,
Maria

**Comment by gvagenas** [comment]
@maria-farooq excellent work. Merged and pushed to master.

What will be your next task ? :)

**Comment by maria-farooq** [comment]
Thanks @gvagenas,

What should be the status of ticket #78 ? I see it is still open, should we close it or ?
As my branch is successfully merged, I would prefer deleting my branch to save space.

About my next work, I can go though issue list or if you have any recommendation please guide?

Regards,
Maria

**Comment by gvagenas** [comment]
@maria-farooq yes please close issue #78 and you can remove your local branch.

I will send you suggested issues to pick what you will work next

**Pull request merged**
